-- return {
--
-- 	"bluz71/vim-nightfly-colors", 
-- 	name = "nightfly", 
-- 	lazy = false, 
-- 	priority = 1000,
-- 	config = function ()
-- 		require('monokai').setup {}
-- 	end,
-- 	"tanvirtin/monokai.nvim",
--
-- 	palette = require('monokai').pro
-- }
--
-- return {
--   "zootedb0t/citruszest.nvim",
--   version = "*",
--   name="citruszest",
--   config = function ()
--     require("citruszest").setup {}
--   end,
-- }
return {}
-- --
